version: '3.5'

services:

# Elasticsearch

  elasticsearch:
    build:
      context: ./elasticsearch
    image: comoyi/elasticsearch:7.5.0
    container_name: elasticsearch
    ports:
      - ${ELASTICSEARCH_HTTP_PORT}:9200
      - ${ELASTICSEARCH_PORT}:9300
    networks: 
      - elastic-stack
    volumes:
      - ./elasticsearch/config:/usr/share/elasticsearch/config:ro
      # - ${ELASTICSEARCH_DATA_PATH}:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"

# Kibana

  kibana:
    build:
      context: ./kibana
    image: comoyi/kibana:7.5.0
    container_name: kibana
    ports:
      - ${KIBANA_PORT}:5601
    networks: 
      - elastic-stack
    volumes:
      - ./kibana/config:/usr/share/kibana/config:ro
      - ${KIBANA_DATA_PATH}:/usr/share/kibana/data
    depends_on:
      - elasticsearch

# Logstash

  logstash:
    build:
      context: ./logstash
    image: comoyi/logstash:7.5.0
    container_name: logstash
    networks: 
      - elastic-stack
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/config:/usr/share/logstash/config:ro

# Filebeat

  filebeat:
    build:
      context: ./beats/filebeat
    image: comoyi/filebeat:7.5.0
    container_name: filebeat
    networks: 
      - elastic-stack
    depends_on:
      - elasticsearch
      - kibana

networks: 
  elastic-stack:
    name: elastic-stack
